# Generated by Django 3.0.5 on 2021-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(default='', max_length=70)),
                ('size', models.CharField(default='', max_length=70)),
                ('toppings', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
